# redis
REDIS_CONNECT_IP = '127.0.0.1'
REDIS_CONNECT_PWD = 'test'


POSTGRESQL_CONNECT_HOST = '127.0.0.1'
POSTGRESQL_CONNECT_ACCOUNT = 'xxx'
POSTGRESQL_CONNECT_PWD = 'test'
POSTGRESQL_CONNECT_DB = 'mmp_dev'
POSTGRESQL_CONNECT_PROT = '5432'

# mmp_dev
POSTGRESQL_WISTRONCONNECT_HOST = '127.0.0.1'
POSTGRESQL_WISTRONCONNECT_ACCOUNT = 'xxx'
POSTGRESQL_WISTRONCONNECT_PWD = 'test'
POSTGRESQL_WISTRONCONNECT_DB = 'mmp_dev'
POSTGRESQL_WISTRONCONNECT_PROT = '5432'