# redis
REDIS_CONNECT_IP = '52.187.73.229'
REDIS_CONNECT_PWD = 'Changeit!123'


POSTGRESQL_CONNECT_HOST = 'mmp-postgresql.postgres.database.azure.com'
POSTGRESQL_CONNECT_ACCOUNT = 'admin_mmp@mmp-postgresql'
POSTGRESQL_CONNECT_PWD = 'Changeit!123'
POSTGRESQL_CONNECT_DB = 'mmp_dev'
POSTGRESQL_CONNECT_PROT = '5432'

# mmp_dev
POSTGRESQL_WISTRONCONNECT_HOST = 'mmp-postgresql.postgres.database.azure.com'
POSTGRESQL_WISTRONCONNECT_ACCOUNT = 'admin_mmp@mmp-postgresql'
POSTGRESQL_WISTRONCONNECT_PWD = 'Changeit!123'
POSTGRESQL_WISTRONCONNECT_DB = 'mmp_dev'
POSTGRESQL_WISTRONCONNECT_PROT = '5432'