from enum import Enum


class DailyManagementPageTableCategoriesType(Enum):
    PCODETOP10_PUCHASE_PER_SITE = 1
    PCODE_PO_LIST = 2
    VENDORTOP10_PUCHASE_PER_SITE = 3
    VENDORTOP10_PO = 4
    EIGHTCATEGORIES_PUCHASE_PER_SITE = 5
    EIGHTCATEGORIES_PO = 6
    PAYMENTTERM_PUCHASE_PER_SITE = 7
    PAYMENTTERM_PO = 8
    PO_LINE_LIST = 9

    PCODE_TOP10 = "A"
    VENDOR_TOP10 = "B"
    EIGHTCATEGORIES = "C"
    PAYMENTTERM = "D"
